version: '3'

services:
  tnt-test:
    image: tarantool/tarantool:2.6.3
    ports:
      - "3301:3301"
    volumes:
      - ./src:/opt/tarantool/
    command: ["tarantool", "/opt/tarantool/app.lua" ]
